### ISSUE TITLE
How to parse image level data into part level data

### ISSUE THREAD

**Issue by ProvenceStar** [facebookresearch/VLPart#3]
Hi, I very appreciate your work and I would like to follow your work and apply it to recent tasks, but I wonder how could I visualize these image-level data that were parsed into part-level data, I found out that in configs folder there is another folder named ann_parser which contains the config file to parse data. However, when I use the config file "find_ins_mixer.yaml" it went wrong with "FileNotFoundError: [Errno 2] No such file or directory: 'output_basedata_pascalpart' ", I would like to know that what command should I run and how should I prepare datasets for visualizing those images that were parsed into part-level data, thanks.

**Comment by PeizeSun** [comment]
Hi~
You need to first run `python train_net.py --num-gpus 8 --config-file configs/ann_parser/build_pascalpart.yaml --eval-only
` to get the directory: 'output_basedata_pascalpart'. The details are in [MODEL_ZOO](https://github.com/facebookresearch/VLPart/blob/main/MODEL_ZOO.md#cross-dataset-part-segmentation-on-partimagenet).

**Comment by ProvenceStar** [comment]
I appreciate your answer, I found out that when I run the code using the command  you give, an error occured "Non-existent config key: MODEL.PIXEL_NORM". After I change MODEL.PIXEL_NORM, MODEL.PIXEL_MEAN and MODEL.PIXEL_STD into DINO.PIXEL_NORM, DINO.PIXEL_MEAN and DINO.PIXEL_STD in the config file, it seems work fine. Thank you for your reply!
